### ISSUE TITLE
Bad formatting on the processed names 

### ISSUE THREAD

**Issue by maikol-solis** [foxfriday/ink#3]
Hi, I just install your package and let me tell you it's wonderful. 

However, I have this problem when I try to include a new figure. This is more or less the workflow that I am following in an org file:

1. `M-x ink-make-figure`. Type `test`. 
2. It opens Inkscape and I draw something.
3. I return to Emacs and execute `M-:` to eval `(ink-process)` **(For better ergonomics, this function could be interactive)**   
4. It appears in the buffer the following snippet:
```
#+NAME: fig:test
[[file:figures/test.png]]
```

The problem is the files are renamed with `svg.png`, like this: 
![image](https://github.com/foxfriday/ink/assets/4078489/88997316-7f4a-4234-b310-51bc52f80aa3)

I don't know if I did something wrong, but any assistance is appreciated. 

Best.

**Comment by foxfriday** [comment]
No need to run ink-process. Just save the file and close Inkscape.

**Comment by maikol-solis** [comment]
Oh I see. Yes it works. Thanks. 

However, I still have the bad naming thing on my files.

**Comment by foxfriday** [comment]
Before continuing, can you delete the figure directory and try again without running ink-process? Just run ink-make-figure, type “test”, draw something, save with ctrl-s and quit with with ctrl-q.

If that doesn’t solve it, I need some more info.

1) Did you change any variable like ink-flags-png?
2) what version of Inkscape are you using?
3) Are you on Windows? I don’t have access to a windows machine so I may not  be able to help.
4) can you give me the messages in the ink-log buffer?

**Comment by foxfriday** [comment]
I assume the issue was resolved.
